From: Example Sender <sender@example.net>
To: Example Receiver <receiver@example.net>
Subject: HTML Body
Date: Fri, 4 Nov 2016 14:22:14 -0400
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8">
  </head>
  <body bgcolor="#FFFFFF" text="#000000">
    Some html text.<br>
    <br>
    A bit more.<br>
    <br>
    Why not a little more.<br>
    <br>
    <b>bold text even</b><br>
  </body>
</html>
