From: Example Sender <sender@example.net>
To: Example Receiver <receiver@example.net>
Subject: HTML Body
Date: Fri, 4 Nov 2016 14:22:14 -0400
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
content-transfer-encoding: quoted-printable

<html><html><html><head><meta content=3D"text/html; charset=3Dutf-8" http-e=
quiv=3D"content-type" /></head><body bgcolor=3D"#FFFFFF" text=3D"#000000">
    Some html text.<br /><br />
    A bit more.<br /><br />
    Why not a little more.<br /><br /><b>bold text even</b><br /><div id=3D=
"heavy-footer" style=3D"width: auto; margin: 0">
Better Faster Stronger =E2=80=A6<br />
https://example.net/groups/bfs =E2=80=A6<br />
Powered by Perl =E2=80=A6<br />
</div>
</body></html></html></html>=
