From: Example Sender <sender@example.net>
To: Example Receiver <receiver@example.net>
Subject: Signed
Date: Fri, 4 Nov 2016 14:32:52 -0400
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Thunderbird/38.6.0
MIME-Version: 1.0
Content-type: multipart/mixed; boundary="----------=_1478284587-6789-0"

This is a multi-part message in MIME format...

------------=_1478284587-6789-0
Content-Type: multipart/signed; micalg=pgp-sha1;
 protocol="application/pgp-signature";
 boundary="ODgUKw0S5l08PXCACCSjBmwqRHnhjhcs0"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--ODgUKw0S5l08PXCACCSjBmwqRHnhjhcs0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable



On 11/04/2016 02:31 PM, Matthew Horsfall wrote:
> This here be a signed message.
>=20
> Sure do.
>=20

Sure is! Signed response too.

>=20
>-------------------------------------------
>Better Faster Stronger =E2=80=A6
>https://example.net/groups/bfs =E2=80=A6
>Powered by Perl =E2=80=A6
>

--ODgUKw0S5l08PXCACCSjBmwqRHnhjhcs0
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQIcBAEBAgAGBQJYHNRUAAoJEOSIO6X7PWARfvYP/jFYnZsT24dqR1Lh+wRGFh/S
74BHFb2Pd+6ngNSzhZ1ARLGnWJeCHYdicjcCIY7/KTwQQVJN7QCNBiQqhmC1fPKw
d5uhLcXDzaaCgVggehTTEOcfl4X1HDfiiejchbpxigt0EGTeA/zbI/RZGJBTCXMc
vo8SJ5VIissPzX8thoVQL5NvHzh+FY3qCDYMkGn8ZuZ6mzS/Ve79NmjdrgWmFTkW
w4t3b/BmdQBk+35UmRZjwHfehnMxbklWyArnzjpdfuxjnVMPPRwDdCadWdIfx9SM
eCPhNVyw2YaIdOjAp2qmKTqCx90g3gbBQtQJ48ML+yrjCdo+cu2xXp1uc2QETIEr
+RfoRTMMVwfS47kkSOryQvPsWWZ8kG4kXTSAuNT//Swurdm71ToHj/xsDG2yDvnk
OhlXKYpJtB7SGZwgao8sD+URd0DVGt7gA0sQT1QdCjlaV5r9bpgCiEGo7EFxihFy
VfwSpEB2+N3Bp9FPgVAkRpuUmTdDSamSbNQ6noMoigDeNbsPZ6/DvSaSRFXRPk4h
26Qp0SkGy7fTVFW/mpEfiejDI90vw+wnPn6T3PcQRlpC86qJPUWHd+enAHTOgcum
6LAriDPYDuENsL8Cy0d7XHkjOY8HamAgGWDgkdarE2Rkr9mCupdvM7v7Wdb9cgK/
Ju5SuV0rLmQlfz2hOrC5
=KdbU
-----END PGP SIGNATURE-----

--ODgUKw0S5l08PXCACCSjBmwqRHnhjhcs0--

------------=_1478284587-6789-0
Content-Type: text/plain; charset="UTF-8"
Content-Disposition: inline
MIME-Version: 1.0
X-Mailer: MIME-tools 5.505 (Entity 5.505)
Content-Transfer-Encoding: quoted-printable


------------------------------------------
Better Faster Stronger =E2=80=A6
https://example.net/groups/bfs =E2=80=A6
Powered by Perl =E2=80=A6

