Date: Fri, 04 Nov 2016 12:03:28 -0400
From: Example Sender <sender@example.net>
To: Example Receiver <receiver@example.net>
MIME-Version: 1.0
Subject: A test message
Content-Transfer-Encoding: 7bit
Content-Transfer-Encoding: 7bit
Content-Type: multipart/mixed; boundary="_----------=_149118122329790551"


--_----------=_149118122329790551
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_149118122329790550"
Content-ID: <14911812280.cD87a05.98950@tb-core1>

This is a multi-part message in MIME format.

--_----------=_149118122329790550
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"

This is a test message=


--_----------=_149118122329790550
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="utf-8"

<html><head><title>hi</title></head><body><div>This is a test message.</bod=
y></html>

--_----------=_149118122329790550--


--_----------=_149118122329790551
Content-Disposition: attachment; filename="amessage.eml"
Content-Transfer-Encoding: 8bit
Content-Type: message/rfc822; name="amessage.eml"

Date: Sat,  1 Apr 2017 06:32:57 -0400 (EDT)
From: someone@example.net
Subject: A subject
To: someoneelse@example.net
MIME-Version: 1.0

This is a message

--D14916E265.1491042777/tb-core1.topicbox.com

--_----------=_149118122329790551--
