From: Example Sender <sender@example.net>
To: Example Receiver <receiver@example.net>
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="UTF-8"
Date: Fri, 04 Nov 2016 12:03:28 -0400
Subject: A test message

This is a simple test message.


------------------------------------------
Better Faster Stronger =E2=80=A6
https://example.net/groups/bfs =E2=80=A6
Powered by Perl =E2=80=A6
