From: Example Sender <sender@example.net>
To: Example Receiver <receiver@example.net>
Subject: Re: HTML Body
Date: Fri, 4 Nov 2016 14:27:00 -0400
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <meta content=3D"text/html; charset=3Dutf-8"
      http-equiv=3D"Content-Type">
  </head>
  <body bgcolor=3D"#FFFFFF" text=3D"#000000">
    On 11/04/2016 02:25 PM, Matthew Horsfall wrote:<br>
    <blockquote
cite=3D"mid:1478283948.2017393.777732297.5D4C6AE5@webmail.messagingengine.c=
om"
      type=3D"cite">
      <title></title>
      <div>On Fri, Nov 4, 2016, at 02:22 PM, Matthew Horsfall wrote:<br>
      </div>
      <div>&gt; Some html text.<br>
      </div>
      <div><br>
      </div>
      <div>Noted.<br>
      </div>
    </blockquote>
    <br>
    Also noted.<br>
    <br>
    <blockquote
cite=3D"mid:1478283948.2017393.777732297.5D4C6AE5@webmail.messagingengine.c=
om"
      type=3D"cite">
      <div><br>
      </div>
      <div>&gt;<br>
      </div>
      <div>&gt; A bit more.<br>
      </div>
      <div><br>
      </div>
      <div>Noted again.<br>
      </div>
    </blockquote>
    <br>
    Ditto.<br>
    <br>
    <blockquote
cite=3D"mid:1478283948.2017393.777732297.5D4C6AE5@webmail.messagingengine.c=
om"
      type=3D"cite">
      <div><br>
      </div>
      <div>&gt;<br>
      </div>
      <div>&gt; Why not a little more.<br>
      </div>
      <div>&gt;<br>
      </div>
      <div><br>
      </div>
    </blockquote>
    Cool<br>
    <br>
    <blockquote
cite=3D"mid:1478283948.2017393.777732297.5D4C6AE5@webmail.messagingengine.c=
om"
      type=3D"cite">
      <div>Well okay!<br>
      </div>
      <div id=3D"heavy-footer" style=3D"width: auto; margin: 0">
      Better Faster Stronger =E2=80=A6<br />
      https://example.net/groups/bfs =E2=80=A6<br />
      Powered by Perl =E2=80=A6<br />
      </div>
    </blockquote>
    <br>
  </body>
</html>
