From: Example Sender <sender@example.net>
To: Example Receiver <receiver@example.net>
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Date: Fri, 04 Nov 2016 12:03:28 -0400
Subject: A test message
Content-Type: multipart/alternative; boundary="14785336930.d851.10651"

--14785336930.d851.10651
Date: Mon, 7 Nov 2016 10:48:13 -0500
MIME-Version: 1.0
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<html><html><html><head><title>hi</title></head><body><div>This is a test m=
essage.</div><div id=3D"heavy-footer" style=3D"width: auto; margin: 0">
Better Faster Stronger =E2=80=A6<br />
https://example.net/groups/bfs =E2=80=A6<br />
Powered by Perl =E2=80=A6<br />
</div>
</body></html></html></html>=

--14785336930.d851.10651
Date: Mon, 7 Nov 2016 10:48:13 -0500
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

This is a test message

------------------------------------------
Better Faster Stronger =E2=80=A6
https://example.net/groups/bfs =E2=80=A6
Powered by Perl =E2=80=A6

