From: Example Sender <sender@example.net>
To: Example Receiver <receiver@example.net>
Subject: Signed
Date: Fri, 4 Nov 2016 14:31:28 -0400
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Thunderbird/38.6.0
MIME-Version: 1.0
Content-type: multipart/mixed; boundary="----------=_1478284323-72567-0"

This is a multi-part message in MIME format...

------------=_1478284323-72567-0
Content-Type: multipart/signed; micalg=pgp-sha1;
 protocol="application/pgp-signature";
 boundary="KnCXOk022nWhEkookfCxFvPKOOla0Uu4I"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--KnCXOk022nWhEkookfCxFvPKOOla0Uu4I
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

This here be a signed message.

Sure do.


--KnCXOk022nWhEkookfCxFvPKOOla0Uu4I
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQIcBAEBAgAGBQJYHNQBAAoJEOSIO6X7PWARXmYP/3N+rNWi0ywpFJnylrxXJlUs
Gbj//8ivyiuJM1RfChaKQna2IIAQKD1HR60Z/TLWE1FA7FOVnqsby6qtCajYzloS
CrSty6a0OvUy1MrZKEUth7IOeFcAV+OKuoBfH0joL2plfW6L8Ujrx1PFRFV7jacG
FJHTXn6XtN0CfAnsFBvq03T52yuuhiix8LOcvGAL6DoIZX5KXPMYK6hDR6ncOPUb
KAZR/kl6E5mumPBAyoJ+soph+FKSGKQm3FVnFvvLnPI3vsBPqE1LTzmGfew3Or9v
TAnMK/Tqm2+oO5CghxXtCzSqyjKNICAZoDSEE8DR+03xiltmUrHA2SDWEEeK+/Jf
XULjvcEFbp9oNOlzJsSa/BfevLE26z0sbmRb3a1jmfJhR36OITYF/3IIL4LxgFOh
tnHjW3xtfW/iSVWAiuhya85/ZGC9sTDjbtMMGLRGCGE74WJwlniMcGQNRVZZr7yS
XOzgbjSxS7bjxVAO79djrIQeXBqfvM1JRBUdI4TWcImSwuxxWEWaixBnjliLwcfX
tqrYnlXOg9pNq1kcUU0e8Y/AsNNe2TMwN71f32gvVIPtCF70vEwAPia62+sZxT+b
9a2qwbus3Jdu90fJHqKKDoPI9pQwyI146BaKhiZa+GoHT6XeVJHuvEh5TdvVnFl9
M9oSG24Y20Lv2xW6sW5F
=rpTq
-----END PGP SIGNATURE-----

--KnCXOk022nWhEkookfCxFvPKOOla0Uu4I--

------------=_1478284323-72567-0
Content-Type: text/plain; charset="UTF-8"
Content-Disposition: inline
MIME-Version: 1.0
X-Mailer: MIME-tools 5.505 (Entity 5.505)
Content-Transfer-Encoding: quoted-printable


------------------------------------------
Better Faster Stronger =E2=80=A6
https://example.net/groups/bfs =E2=80=A6
Powered by Perl =E2=80=A6

