From: Example Sender <sender@example.net>
To: Example Receiver <receiver@example.net>
Date: Fri, 04 Nov 2016 12:03:28 -0400
MIME-Version: 1.0
Subject: A test message
Content-Type: multipart/mixed; boundary="14928047760.36Dfd.14226"
Content-Transfer-Encoding: 7bit


--14928047760.36Dfd.14226
Date: Fri, 21 Apr 2017 15:59:36 -0400
MIME-Version: 1.0
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

Hello there
--14928047760.36Dfd.14226
Date: Fri, 21 Apr 2017 15:59:36 -0400
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"; name="attach.txt"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

Inline attachment !=

--14928047760.36Dfd.14226--
